### ISSUE TITLE
cannot delete cron event

### ISSUE THREAD

**Issue by mastef** [johnbillion/wp-crontrol#1]
i have a weird issue, where multiple instances of a single instance cron event are ran at every wp-cron iteration. the cron events themselves are not removed after successful execution, and neither does `wp crontrol delete-event EVENT` remove them, although it executes properly.

i have a hunch that it might be due to database values having been edited/replaced after the single events have been scheduled. could this be the case? e.g. what is wp looking for when trying to delete a cron event?

**Comment by johnbillion** [comment]
This should be fixed in WP Crontrol 1.3.
