### ISSUE TITLE
Possible conflict with newer versoins of Wordpress - Unexpected HTTP response code: 412

### ISSUE THREAD

**Issue by iowaprogressives** [johnbillion/wp-crontrol#10]
Unfortunately I'm not as savvy as most the folks that post on here but here's what I know.

I'm using WP RSS Aggregator on my site to import RSS feeds and I purchased their option to post to feed. This is the addon they recommend to manage cron jobs. I've gone through all their work throughs and called up Godaddy who is my host currently and they ran tests and cron is working properly on my server.
They said however that they noticed that crontrol is not test for my version of WP which is 4.8 and that may be causing the conflict that is making the aggregator to not function properly. My site is iowaprogressives.com and it worked at one point, but I did update wp so it could make sense that the update made the plugin incompatible. Anyways, I'm hoping you guys can please help me out. This is such a big piece of my site! Anyways, please and thank you :)

**Comment by iowaprogressives** [comment]
There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was: 
Unexpected HTTP response code: 412

That's the full error that I get from crontrol.

**Comment by johnbillion** [comment]
https://wordpress.org/support/topic/there-was-a-problem-spawning-a-call-to-the-wp-cron-system-on-your-site-this-mea-2/#post-9252058
