### ISSUE TITLE
Can't delete

### ISSUE THREAD

**Issue by kay83483023423v** [johnbillion/wp-crontrol#104]
Hi

I was wondering whether you could help - we can't seem to delete the cron jobs, tried to deactivate all the plugins in case it was clashing and cleared the caches from the server however we're still having the same issue.

**Comment by johnbillion** [comment]
Unfortunately I can't be of much help with this issue beyond what I've written here: https://github.com/johnbillion/wp-crontrol/wiki/Problems-adding-or-editing-WP-Cron-events . I hope that helps, and good luck!
