### ISSUE TITLE
Missing hooks

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/wp-crontrol#114]
Is there a way in wp-crontrol to spot cron events without registered hooks?

```shell
wp eval 'array_map(function($c){$h=array_key_first($c);if(!has_action($h))echo $h,"\n";},_get_cron_array());'
```

**Comment by johnbillion** [comment]
Yes the Tools -> Cron Events screen shows a warning when an event doesn't have a callback registered for the action.

https://wordpress.org/plugins/wp-crontrol/#what%20does%20it%20mean%20when%20%22none%22%20is%20shown%20for%20the%20action%20of%20a%20cron%20event%3F

**Comment by szepeviktor** [comment]
Thank you.
