### ISSUE TITLE
PHP 8.3 warning

### ISSUE THREAD

**Issue by knutsp** [johnbillion/wp-crontrol#133]
`PHP Warning:  Increment on type bool has no effect, this will change in the next major version of PHP in */wp-crontrol/src/bootstrap.php on line 641`

The variable `$deleted` contains the return value from `Event\delete()` and this method will return boolean true on success.

**Comment by johnbillion** [comment]
Thanks! I've seen this myself and been trying to figure out why PHPStan isn't flagging it during the coding standards tests. I think I need to up the strictness of its rules.

**Comment by johnbillion** [comment]
Ah no it's to do with the strict ruleset. https://github.com/phpstan/phpstan/discussions/11613. I'll get this fixed in the next release.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
