### ISSUE TITLE
Wordfence found your update malicious

### ISSUE THREAD

**Issue by olya-fb** [johnbillion/wp-crontrol#14]
Hi,

After updating your plugin to the latest version today, I got this message from Wordfence (after its scan):

"Critical Problems:

* This file may contain malicious executable code: /home/allowmoney/www/www/blog/wp-content/plugins/wp-crontrol/wp-crontrol.php"

Can you please confirm that it's a false positive?

Thank you!
Olga.

**Comment by johnbillion** [comment]
You'll need to manually check to ensure your update wasn't compromised. There's not enough detail in that report to make an informed decision (you should ask Wordfence about that).

There's no malicious code in WP Crontrol.

**Comment by asarosenberg** [comment]
As stated in the scan result - The file was detected because you have enabled HIGH SENSITIVITY scanning. High sensitivity will flag any code using eval in combination with encoding. You can disable high sensitivity scanning unless you have reason to suspect that your site is infected.

**Comment by olya-fb** [comment]
thank you John, I did the scan after plugin update

thank you Asa, I now saw the eval in your code, indeed.

so you're sure your eval can't be misused?

**Comment by johnbillion** [comment]
> so you're sure your eval can't be misused?

Good question. The `eval()` code is used to execute a PHP cron event. Users can only add or edit a PHP cron event if they have the `edit_files` capability (a WordPress core capability), which is only granted to Administrators on single site installations, and Super Admins on Multisite installations. In addition, this capability is not granted to any user if the `DISALLOW_FILE_EDIT` constant is defined.

**Comment by olya-fb** [comment]
ok, thank you!
