### ISSUE TITLE
"Run now" does nothing for hooks on an interval <= 10 minutes

### ISSUE THREAD

**Issue by zytzagoo** [johnbillion/wp-crontrol#2]
It seems to be related to https://core.trac.wordpress.org/browser/tags/4.1.1/src/wp-includes/cron.php#L23

To quickly test it I've just appended a random value to the end of `$args` in `run_cron()` and it indeed busts/avoids the core's "identical event" check (and starts running those hooks properly): https://github.com/zytzagoo/wp-crontrol/commit/05a58e67dbdfcafc3e1e94810eb0997392a2a6fe

Any ideas/suggestions for a "proper" fix?

**Comment by johnbillion** [comment]
It's unlikely I'll ever fix this in WP Crontrol. WordPress core doesn't support schedules shorter than 10 minutes.
