### ISSUE TITLE
Don't show a checkbox next to PHP cron events that can't be deleted

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/wp-crontrol#20]
Follow-up to #16 . The `Delete` link is now not shown, but the checkbox is still shown. It should be hidden according to the same logic.

**Comment by cfoellmann** [comment]
this is closed, right?

**Comment by johnbillion** [comment]
Nope this still needs to be done, if I recall correctly.

**Comment by cfoellmann** [comment]
![2018-06-26 1](https://user-images.githubusercontent.com/1256090/41914624-fdfecf2c-7953-11e8-98c7-cb4802e85d36.png)

Current wp.org version

**Comment by johnbillion** [comment]
Thanks! This ticket is specifically for the PHP cron jobs, not regular cron jobs, where the checkboxes are correctly hidden.

**Comment by cfoellmann** [comment]
Sorry
