### ISSUE TITLE
segmentation fault on PHP 7.1.11

### ISSUE THREAD

**Issue by khromov** [johnbillion/wp-crontrol#21]
Version 1.6.2 reliably gives me a segfault on the "Cron Events" page when using PHP 7.1.11 (built-in web server) on OSX. 1.5 does not segfault.

**Comment by johnbillion** [comment]
Thanks for the report. I'm running PHP 7.1.0 locally and I don't see any problems. I'll update to .11 and see if anything changes.

I thought the problem might be related to the `Actions` column on that screen, but that's also present in 1.5.

Can you take a look in your PHP error log and see if there's a specific message in there that can help me pinpoint the problem?

**Comment by khromov** [comment]
@johnbillion PHP typically doesn't give you a backtrace for segfault, I'll try to enable debug or isolate the code causing the issue.

**Comment by johnbillion** [comment]
Let me know if you found the cause of this.
