### ISSUE TITLE
Time Field on Add Cron Job not working in Firefox

### ISSUE THREAD

**Issue by brent-leavitt** [johnbillion/wp-crontrol#24]
Link to Page with Issue: wp-admin/tools.php?page=crontrol_admin_manage_page

I've found this bug in Firefox, in the 'Add Cron Job' tab on the **Tools -> Cron Events** page the time field is not letting me proceed. I think this is HTML pre-validation check that Firefox is doing on the time field. I opened up the  HTML code in the inspector window and switch the time field to a standard text field. I also removed the 'step' attribute, per this little bit of advice: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attribute. 

But in hind-sight, i think the real issue was just with the field length being set to 8, instead of 11. The time field was displaying "--:--:-- --" (note the additional milliseconds field at the end.) At any rate, the experience was buggy. 

But thanks for a great plugin!

**Comment by johnbillion** [comment]
Thanks for the report. The date and time picking fields have been a bit problematic. Their implementation was a bit of wishful thinking on my part. I think I'll switch them back to plain text inputs.

**Comment by brent-leavitt** [comment]
You're welcome. I get the optimism, hoping that it will just work! The date picker worked like a charm on Firefox, but I've not tested in any other browser.

**Comment by johnbillion** [comment]
Fixed in 1.7.0. I switched back to a plain text field and some preset options.
