### ISSUE TITLE
5 minutes cron job keeps getting deleted

### ISSUE THREAD

**Issue by tom-acservices** [johnbillion/wp-crontrol#26]
We are currently running a script that suppose to check every 5 minutes if payments are completed. This works fine for a bit. But after a while the cron job just disappears for no explainable reason

**Comment by johnbillion** [comment]
The minimum time for a WP-Cron schedule is ten minutes. This is a restriction inside WordPress core, nothing to do with WP Crontrol.

I'll add a note to the Cron Schedules screen to help with this.

**Comment by johnbillion** [comment]
Oh, turns out that's not _entirely_ accurate. From [the docs for `wp_schedule_event()`](https://developer.wordpress.org/reference/functions/wp_schedule_event/):

> Note that scheduling an event to occur within 10 minutes of an existing event with the same action hook will be ignored unless you pass unique `$args` values for each scheduled event.
