### ISSUE TITLE
New field still displayed after deleting it.

### ISSUE THREAD

**Issue by jphilippou** [johnbillion/wp-crontrol#27]
I wanted to see the capabilities assigned to a user, so I added a new field 'Capabilities' with meta wp_capabilities and selected Display []. The Capabilities column showed up when I selected Users->All users but didn't have the user's capabilities. That isn't the issue (although it might be one).

The issue is I deleted the field while Display[] was still checked and when I selected Users->All users, the Capabilities column was still there even after I deleted it. I added it again it didn't show up twice, but WP reported an error about passing an array (I should have copied it for this bug report). I went back to the WP-Control fields unchecked Display[] and saved the changes, then removed the Capabilities field; this removed the column from All users.

**Comment by johnbillion** [comment]
I'm sorry but I've no idea what you're talking about. This isn't related to the WP Crontrol plugin.
