### ISSUE TITLE
"Run Now" and `DISABLE_WP_CRON` result in uncleared scheduled events

### ISSUE THREAD

**Issue by mikeschinkel** [johnbillion/wp-crontrol#30]
I submitted a [pull request](https://github.com/johnbillion/wp-crontrol/pull/29) for this.  You can see the [logic and comments](https://github.com/johnbillion/wp-crontrol/pull/29/files#diff-5cb3776f36e5d5cfe93fab733d54f76aR461) about it here, lines `461..484`.

**NOTE: Seems GitHub has broken links to specific lines in code. Ugh.**

**Comment by johnbillion** [comment]
Thanks for the fixes Mike. I'll see if I can find some time next week to review.
