### ISSUE TITLE
Cron Job Not Triggerign On Time

### ISSUE THREAD

**Issue by preetssekhon** [johnbillion/wp-crontrol#32]
First of all i would like to mention this is awesome plugin. But there is one issue regarding cron job triggering time. I have number of cron jobs but those jobs are not triggering on time its taking some time. Like if i have setup cron job to trigger at 7 am but its triggering on 7:40 am sometimes at 8:00 am, i mean to say not triggering on time. Please help.

**Comment by johnbillion** [comment]
Unfortunately this is unrelated to WP Crontrol. Cron jobs in WordPress will only fire if your website is actively receiving traffic, and even then a cron job is not guaranteed to fire at the exact time that it's scheduled.

More info here: https://code.tutsplus.com/articles/insights-into-wp-cron-an-introduction-to-scheduling-tasks-in-wordpress--wp-23119
