### ISSUE TITLE
Daylight savings

### ISSUE THREAD

**Issue by MrFent** [johnbillion/wp-crontrol#34]
When daylight savings time ends and begins, the time for scheduled events gets shifted. Need compatibility for daylight savings.

**Comment by johnbillion** [comment]
Thanks for the report!

This is most likely a problem with WordPress core, I know from memory there are problems with things such as scheduled posts not publishing at the correct time due to daylight savings. Do you think there's anything specific that WP Crontrol needs to do to handle daylight savings?

**Comment by MrFent** [comment]
When a website's timezone is set to UTC+-, things can get messed up when dealing with Daylight Savings, but when it's set to a location, like Chicago, etc... the time shifts automatically. My site is set to a location, so everywhere else, the time adjusts like it should. WP Crontrol acts like the site is set to UTC+-/

**Comment by johnbillion** [comment]
I think in that case it's not a problem specific to WP Crontrol (it's just an interface to the cron events system in WordPress core after all).

That said, I'll see if I can find some time to double check its behaviour and see if I can find any related bugs reported in WordPress Core Trac.

**Comment by MrFent** [comment]
Awesome, thanks! It's not a huge deal, I just have to remember to update a couple cron events twice a year when daylight savings ends and begins, but still kinda annoying.

**Comment by johnbillion** [comment]
Closing this off as there's nothing specific here that WP Crontrol can do to help. Since this bug was reported I've added even further clarity around timezones everywhere a time is displayed by the plugin, hopefully that helps.
