### ISSUE TITLE
Runaway Cron job

### ISSUE THREAD

**Issue by plainjoe** [johnbillion/wp-crontrol#35]
I have a Cron job that is scheduled to run once a day at 11:30PM PST.  It runs PHP code and email a bunch of people.  It's been running fine for months but suddenly it started to run ~306 times from 1:40AM to 1:51AM the following day, then stops.  Is there anything I can look at to debug this issue ?  Thanks.

**Comment by johnbillion** [comment]
Thanks for the report. Is this specific to WP Crontrol? Does it still happen with this plugin deactivated and/or with another cron management plugin active instead?

**Comment by plainjoe** [comment]
I only use WP Crontrol as a cron management plugin.  I will try another and let you know.  Thanks.

**Comment by plainjoe** [comment]
Are there any logs that I can look at to debug ?

**Comment by johnbillion** [comment]
Unfortunately WordPress doesn't store logs of cron events that fire. It's something that I've been thinking of adding to WP Crontrol, but I haven't had time to work on.
