### ISSUE TITLE
Cron event logging: Limit the log storage

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/wp-crontrol#40]
Limit on the number of logs stored. Either a number or a time frame.

**Comment by angiep** [comment]
Hey @johnbillion! We're currently using `wp-crontrol` in our production environment and recently noticed that we are storing an overwhelming number of `crontrol_log`s.

Is there an easy way for us to disable the cron logs feature?

**Comment by johnbillion** [comment]
Nope, not yet.

**Comment by johnbillion** [comment]
Ah, sorry, you can disable the cron jobs feature by switching to one of the stable versions of Crontrol which doesn't include this feature. The feature only exists on the develop branch currently. So 1.8 from WordPress.org doesn't have the feature.

**Comment by johnbillion** [comment]
Alternatively you can uncheck all the checkboxes on the Cron Logs screen.

**Comment by angiep** [comment]
Thanks for such a quick response! We're going to swap to version 1.8.3 for now.

**Comment by johnbillion** [comment]
Closing this off as it's covered in #19.
