### ISSUE TITLE
"edit" doesn't work when more than one page

### ISSUE THREAD

**Issue by hdpei** [johnbillion/wp-crontrol#48]
URI less "paged=2"

**Comment by johnbillion** [comment]
What do you mean by "doesn't work"? What happens?

**Comment by hdpei** [comment]
It should have been 'Edit PHP Cron Event 'but it showed 'Edit Cron Event'.
If I add "&paged=2" to the URL manually, it works fine

**Comment by johnbillion** [comment]
Thanks, I've identified the problem. I'll get it fixed.

**Comment by johnbillion** [comment]
Fixed in 1.8.3.
