### ISSUE TITLE
RE: Unexpected HTTP response code: 500

### ISSUE THREAD

**Issue by tomsychau** [johnbillion/wp-crontrol#51]
I am running into an error:

There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was:
Unexpected HTTP response code: 500

The plugin is installed  on a multisite.  All site works fine except this one.
www.sushibon.com

Can you tell me what happened?

**Comment by johnbillion** [comment]
Sorry but I can't provide support for problems that you're having on your site, it would be a full time job. Check the error logs for your server and PHP.
