### ISSUE TITLE
Navigation-tabs #crontrol-header element prints above #screen-meta element

### ISSUE THREAD

**Issue by abuyoyo** [johnbillion/wp-crontrol#52]
`#crontrol-header` element prints above `#screen-meta` element and hello-dolly, which is... weird.

Attached is a screenshot.
There's a custom-styled hello-dolly string (other than the css it's the same as the default).
And there's a custom notice-collector plugin that adds a panel to core's `#screen-meta` element - which just makes the weirdness more pronounced. Especially when the panel opens.

Obviously the WP-Crontrol page was not designed with any screen-meta-link panels in mind. Nor does wp-core, at this time, provide any API for adding tabs/panels - so none could be expected. Nonetheless..

![wp-crontrol-header](https://user-images.githubusercontent.com/24979061/89479705-20009300-d79c-11ea-88eb-4fd274fbebd5.jpg)

**Comment by johnbillion** [comment]
Thanks for the report. The positioning of these tabs is intentionally above the Help and Screen Options tab because they represent the ability to switch between different screens that have different help information and different screen options.

That said, you're correct that at best this is inconsistent with other screens, and at worst looks broken. I'll have a think about how I can improve this.

**Comment by abuyoyo** [comment]
Nav-Tabs that switch between different pages of the same plugin, or different pages in the same sub-menu, should semantically appear right below the page title.
Nav-Tabs that switch "outside" the same plugin, or outside a common sub-menu, could perhaps appear right above the main title.
That is what makes the most sense to me.

Screen-Meta Tabs (such as Help and Screen Options) are designed to only work visually as small pull-out panels right from "under" the toolbar. They cannot have any type of empty space above them. An exception could perhaps be made for pages designed similar to site-health. With the top white header occupying the full width under the toolbar. They could pull out from under that white header instead of the toolbar. (tho that's not where core renders them currently on site-health)

**Comment by johnbillion** [comment]
Fixed in b3f5fd8.
