### ISSUE TITLE
wp-crontrol.php fails a couple of antivirus tests

### ISSUE THREAD

**Issue by edwardsmarkf** [johnbillion/wp-crontrol#55]
problem summed up here:

https://wordpress.org/support/topic/wp-crontrol-php-triggering-quttera-error/

**Comment by johnbillion** [comment]
Thanks for the report but this is something you'll need to raise with the supplier of your virus scanner. It looks like the line in question is just a transient deletion, there's certainly no virus there.

Cheers!

**Comment by edwardsmarkf** [comment]
thank you john - my concern was it was not only flagged not only on quttera but also when i uploaded it on https://virusTotal.com.
