### ISSUE TITLE
Possible to retrieve a list of cron events from this plugin as a PHP array?

### ISSUE THREAD

**Issue by chrisblakley** [johnbillion/wp-crontrol#57]
The table of cron events without actions in this plugin is really helpful for removing vestigial cron jobs. For my group, we're looking into mitigating an issue we've been having with tons of these cron events and I've been looking under the hood at this plugin to see if we can basically get that same list of cron events without actions, but as an array in PHP.

I don't see any actions/filters we can hook into from another plugin/theme to retrieve an array like this. I found the `get_filtered_events()` function within `event-list-table.php` but it is a protected function. Obviously it was made protected for a reason, but I'd love to be able to get the `$filtered` return from that– or even just the `$filtered['noaction']` portion from outside.

For my team, my initial hope is to count how many of these cron events without actions exist and come up with an indication system (like an email and/or WP notice) that they need to be addressed. Then someone on the team could go into the plugin table and remove them (or maybe one day we can automate it).

I'm sure I've made this as clear as mud, so to recap:
**Is it possible to use this plugin to retrieve an array of cron events without actions?**

I know I could piecemeal parts of this together to home-grow my own, but I thought I'd ask instead of reinventing the wheel myself.

**Comment by johnbillion** [comment]
Short answer: No.

Long answer: Yeah with a bit of coding you should be able to extract these. The `items` property on the list table is public even though the method you mention is protected, so you could instantiate the list table, populate `$_GET` with your query args, call the `prepare_items()` method, and then read the `items` property to get that list.

Funnily enough I've never had a need to export the list of cron events with WP Crontrol as I use the `wp cron event list` command in WP-CLI for that, but I can certainly see how that would be useful in WP Crontrol too, especially with its filtering.

Another option might be to look at the various CSV export plugins available, and see if any of them allow you to directly export the results of a `WP_List_Table` instance. A quick Google brings up https://github.com/leewillis77/WpListTableExportable but it requires an adjustment to the list table class, but it might work as an interim solution.

**Comment by chrisblakley** [comment]
Thanks for the info and quick response– I'll give those ideas a try.
