### ISSUE TITLE
502

### ISSUE THREAD

**Issue by quantrpeter** [johnbillion/wp-crontrol#58]
hi, i got this. please help

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/50471577/112747010-3c7c6480-8fe5-11eb-8493-99a613dc67f7.png">

**Comment by quantrpeter** [comment]
it tried to send request to /wp-cron.php?doing_wp_cron=1616926151.7406868934631347656250 but got this as returns:

array(6) {
  ["headers"]=>
  object(Requests_Utility_CaseInsensitiveDictionary)#922 (1) {
    ["data":protected]=>
    array(4) {
      ["server"]=>
      string(9) "openresty"
      ["date"]=>
      string(29) "Sun, 28 Mar 2021 10:09:12 GMT"
      ["content-type"]=>
      string(9) "text/html"
      ["content-length"]=>
      string(3) "154"
    }
  }
  ["body"]=>
  string(154) "
["raw"]=>
      string(303) "HTTP/1.1 502 Bad Gateway
Server: openresty
Date: Sun, 28 Mar 2021 10:09:12 GMT
Content-Type: text/html
Content-Length: 154
Connection: close


If i manally browse to it, it works

**Comment by johnbillion** [comment]
Sorry you're having a problem but this isn't something I can help with as it's not a problem with WP Crontrol itself. If you click the "More information" link in the message I've written a bunch of information there that will hopefully help you out. Best of luck!
