### ISSUE TITLE
cURL error 7: Failed to connect to XXXX port 443: Connection refused

### ISSUE THREAD

**Issue by parleer** [johnbillion/wp-crontrol#60]
I'm receiving the following error notification:

```
There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was:

cURL error 7: Failed to connect to XXXX port 443: Connection refused

More information
```

The [More information](https://github.com/johnbillion/wp-crontrol/wiki/Problems-with-spawning-a-call-to-the-WP-Cron-system) page includes this description:

### URL error 7: Failed to connect: Connection refused
This is a bit of a mystery error. It could relate to your HTTPS configuration, or it could be an access restriction problem (see below).

But I think this is quite common in a development environment. The problem is that network topology in a development environment often looks like this: 

```

Web Client    <--->                 Proxy                   <--->            Web server 
                      Docker container listening on 80,443         Docker container listening on 80
                                Mapped to 80,443                        Mapped to Proxy as 26345
```

Where the Web Server container is only listening to port 80. Since WP-Cron is invoked from within the container, it needs to be going http://localhost/wp-cron.php instead of https://localhost/wp-cron.php.

Is there a way to override the WP Cron url so that it uses http instead of https?

**Comment by johnbillion** [comment]
That's a strange setup. Why is your web server not also listening on 443?

Regardless, yes you can adjust the cron URL with [the `cron_request` filter](https://developer.wordpress.org/reference/hooks/cron_request/) but that's not the only place in WP core that performs a server-side request to the site itself. For example, the Tools -> Health Check screen, the theme and plugin editors, the Multisite upgrade routine, some of the block editor asset loading, the importer, and probably other places all do this.
