### ISSUE TITLE
Проблемы отображения

### ISSUE THREAD

**Issue by shopcd** [johnbillion/wp-crontrol#75]
![image](https://user-images.githubusercontent.com/66871213/147407526-9455dddc-07f6-4942-8e6e-4d4133671512.png)
вот так показывает (

**Comment by johnbillion** [comment]
Which browser and operating system are you using please?

Does the problem remain if you switch to English in the admin area?

**Comment by JohnnyBravoTheBest** [comment]
@shopcd Would be nice of you to describe the issue in English.
