### ISSUE TITLE
SSL (Unknown error)

### ISSUE THREAD

**Issue by lietuv1s** [johnbillion/wp-crontrol#79]
Hello, having dificulty tracking this one down:
`There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was:`
`stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://www.my.site:443 (Unknown error)`
Logs (access/error) show me nothing.

Is this sslv3? And not tls? I dont understand. Im using cloudflare. Doesnt cloudflare (and others) outright refuse ssl3? Also why would my site try to connect to itself? I see connection attempts from Turkey (cloudflare fw) but this might be unrelated. Or is it?

**Comment by johnbillion** [comment]
I'm sorry but I can't help with individual issues on sites, it would be a full time job for me! Check out the wiki here which should help you out: https://github.com/johnbillion/wp-crontrol/wiki/Problems-with-spawning-a-call-to-the-WP-Cron-system
