### ISSUE TITLE
possible solution to the problem of the vendor dir not being included in the .org plugin repo

### ISSUE THREAD

**Issue by pbiron** [johnbillion/wp-crontrol#85]
Looking in [Plugins Trac > trunk](https://plugins.trac.wordpress.org/browser/wp-crontrol/trunk) I notice that the `svn:ignore` property includes `vendor`.  The same seems true of all the existing branches.

![wp-crontrol-svn-ignore-vendor](https://user-images.githubusercontent.com/3824560/178163307-b155d07a-fb1e-4937-8d49-b53b3b14304f.png)

Not 100% sure, but I think if you remove `vendor` from that prop, then the `vendor` dir will get committed to SVN, which should solve the recent problems.

**Comment by johnbillion** [comment]
Ohhhhhhhhhhhh very good spot, I've been scratching my head over this because the build on GitHub is fine

**Comment by johnbillion** [comment]
Fixed in https://plugins.trac.wordpress.org/changeset/2754269/wp-crontrol/trunk . Thanks 👍
