### ISSUE TITLE
Custom cron schedule not displaying

### ISSUE THREAD

**Issue by sagotan** [johnbillion/wp-crontrol#9]
http://..../wp-admin/options-general.php?page=crontrol_admin_options_page

After creating new "Weekly" schedule. "Weekly" didn't display in the table or the dropdown select box.

**Comment by sagotan** [comment]
Think you only loop the $schedules but not the $custom_shcedules

foreach ( $schedules as $name => $data ) {
	printf( '<tr id="sched-%s">',
		esc_attr( $name )
	);
	printf( '<td>%s</td>',
		esc_html( $name )
	);
	printf( '<td>%s (%s)</td>',
		esc_html( $data['interval'] ),
		esc_html( $this->interval( $data['interval'] ) )
	);
	printf( '<td>%s</td>',
		esc_html( $data['display'] )
	);
	if ( in_array( $name, $custom_keys ) ) {
		$url = add_query_arg( array(
			'page'   => 'crontrol_admin_options_page',
			'action' => 'delete-sched',
			'id'     => urlencode( $name ),
		), admin_url( 'options-general.php' ) );
		$url = wp_nonce_url( $url, 'delete-sched_' . $name );
		printf( '<td><span class="row-actions visible"><span class="delete"><a href="%s">%s</a></span></span></td>',
			esc_url( $url ),
			esc_html__( 'Delete', 'wp-crontrol' )
		);
	} else {
		echo '<td>&nbsp;</td>';
	}
	echo '</tr>';
}

**Comment by johnbillion** [comment]
I'm unable to reproduce this problem, sorry. Let me know if it's still an issue.
