### ISSUE TITLE
Unable to edit or delete custom cron

### ISSUE THREAD

**Issue by iammichaelgarcia** [johnbillion/wp-crontrol#99]
I created three custom crons, type "WP Crontrol," when I created my website.  Recently, I looked at the crons to update them and noticed I could not update or delete them.  I tried finding them in the DB, but I cannot locate where the content is stored.  Am I doing something wrong?

**Comment by johnbillion** [comment]
Did you disable the ability to edit files in the admin area after you first created your site? If so, you'll no longer be able to manage those PHP cron events. Take a look here for more info:

* https://wordpress.org/plugins/wp-crontrol/#which%20users%20can%20manage%20php%20cron%20events%3F%20is%20this%20dangerous%3F
* https://github.com/johnbillion/wp-crontrol/wiki/PHP-cron-events
